### ISSUE TITLE
Your module uses decimal instead of hex for escaping control characters.

### ISSUE THREAD

**Issue by anall** [kazeburo/JavaScript-Value-Escape#2]
This has also been reported at https://rt.cpan.org/Public/Bug/Display.html?id=74552, and I am reproducing. 

`javascript_value_escape("foo\nbar")` results in `foo\u0010` not `foo\u000abar`

Thank you.

**Comment by cxw42** [comment]
This can be closed since #3 was merged, right?

**Comment by anall** [comment]
Correct.
